apiVersion: v1
kind: ServiceAccount
metadata:
  name: alertmanager
  namespace: open-cluster-management
  labels:
    alertmanager: observability
  annotations:
    serviceaccounts.openshift.io/oauth-redirectreference.alertmanager: '{"kind":"OAuthRedirectReference","apiVersion":"v1","reference":{"kind":"Route","name":"alertmanager"}}'
