kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: allow-db-clients
  namespace: vm
spec:
  namespaceSelector:
    matchLabels:
      allowing: mariadb-server 
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          allowing: db-clients
    ports:
    - port: 3306
      protocol: TCP
