# Copyright (c) 2021 Red Hat, Inc.
# Copyright Contributors to the Open Cluster Management project.
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: endpoint-observability-operator
roleRef:
  kind: ClusterRole
  name: endpoint-observability-operator
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: endpoint-observability-operator
  namespace: open-cluster-management-addon-observability
