## Append samples you want in your CSV to this file as resources ##
resources:
- observability.open-cluster-management.io_v1beta1_observabilityaddon.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
