apiVersion: v1
kind: Service
metadata:
  labels:
    app: rbac-query-proxy
  namespace: open-cluster-management
spec:
  ports:
  - name: http
    port: 8080
    targetPort: http
  selector:
    app: rbac-query-proxy