apiVersion: v1
kind: LimitRange
metadata:
  name: limit-range
  namespace: open-cluster-management-observability
spec:
  limits:
  - max:
      cpu: "5.25"
      memory: "12Gi"
    defaultRequest:
      cpu: "10m"
      memory: "50Mi"
    type: Container
